# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e3ec539c013233ebe9d099d36c907b14"
name = "bundle-threshold-dynamic"
handle = "bundle-threshold-dynamic"
application_url = "https://informational-arkansas-heading-simplified.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "idyl-sandbox-2024.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_discounts,write_products"

[auth]
redirect_urls = [
  "https://informational-arkansas-heading-simplified.trycloudflare.com/auth/callback",
  "https://informational-arkansas-heading-simplified.trycloudflare.com/auth/shopify/callback",
  "https://informational-arkansas-heading-simplified.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
